spring:
  application:
    name: apigateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: micro-server-categorias
              uri: lb://categorias
              predicates:
                - Path=/api/categorias/**
            - id: micro-server-productos
              uri: lb://productos
              predicates:
                - Path=/api/productos/**

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.client.discovery: INFO
