spring:
  application:
    name: productos
  datasource:
    url: jdbc:h2:mem:productosdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  port: 8082

app:
  nombre: "Servicio Productos"
  descripcion: "Configuración centralizada para el microservicio productos"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
